services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - PRIVATE_KEY=${NORDVPN_PRIVATE_KEY}
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv4.ip_forward=1
    ports:
      - '127.0.0.1:9999:9999'
    restart: unless-stopped

  twitch-plays-vim:
    build: .
    network_mode: service:vpn
    tty: true
    stdin_open: true
    volumes:
      - ./playground:/playground
      - ./init.lua:/home/vimuser/.config/nvim/init.lua
    environment:
      - ALLOW_CONSOLE=1
      - TWITCH_CHANNEL=skalkid
    depends_on:
      - vpn
    # Add security configurations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /home/vimuser/.local
      - /home/vimuser/.local/state
      - /home/vimuser/.local/share
      - /home/vimuser/.cache
    # Set resource limits to prevent DoS
    mem_limit: 512m
    memswap_limit: 512m
    pids_limit: 100
    ulimits:
      nproc: 100
      nofile:
        soft: 1024
        hard: 1024
